### ISSUE TITLE
Problem to use it

### ISSUE THREAD

**Issue by arnold-b** [maxpautsch/SvgParser#1]
Hello, 
when i use your demo, it works. 
but when i edit your demo with lnkscape and make an aditional path then i see your sample but not my path. What i´m doing wrong 

Thanks

**Comment by joaoreni** [comment]
Hi arnold, i'm with the same issue! did you make this work?

**Comment by maxpautsch** [comment]
Hi there. If I remember correct, there are different ways, Inkscape can save paths and there was an option to change this. Could you have a look at the svg source code and post the part, which represents the new path?

**Comment by joaoreni** [comment]
Hi Max,

I dig into your library and found what was going on, the library doesn't parse beziers, arcs, etc... And with the SVG framework updates, the styles aren't parsing correctly too.

As I don't have time to implement the solution, I'm working with bitmap images.

just by editing your example index.svg using beziers in "test" letters and adding a new icon, it prints everything except test and the new icon.

here is the original index.svg and the modified index.svg
[svgs.zip](https://github.com/maxpautsch/SvgParser/files/7060164/svgs.zip)

**Comment by maxpautsch** [comment]
Thank you for your feedback. Beziers would be tricky to implement - and as I don't need it personally and I do not know how often the lib is used I do not plan to spend the effort and support them.
